global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
    - targets:
      - '192.168.10.25:7070'
  - job_name: 'kafka'
    static_configs:
    - targets:
      - '192.168.10.37:8080'