#!/bin/bash
    #/etc/init.d/zookeeper
    # Check that networking is up.
    #[ ${NETWORKING} = "no" ] && exit 0

    export EXTRA_ARGS="-javaagent:/home/vagrant/prometheus/jmx_prometheus_javaagent-0.12.0.jar=7070:/home/vagrant/prometheus/zookeeper.yaml"
    # See how we were called.
    case "$1" in
    start)
            # Start daemon.
            pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
            if [ -n "$pid" ]
            then
                echo "Zookeeper is already running";
            else
            /home/vagrant/kafka/bin/zookeeper-server-start.sh  /home/vagrant/kafka/config/zookeeper.properties
            fi
            ;;
    stop)
            echo "Shutting down $DAEMON_NAME";
            $/home/vagrant/kafka/bin/zookeeper-server-stop.sh
            ;;
    restart)
            $0 stop
            sleep 2
            $0 start
            ;;
    status)
            pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
            if [ -n "$pid" ]
            then
            echo "Zookeeper is Running as PID: $pid"
            else
            echo "Zookeeper is not Running"
            fi
            ;;
    *)
            echo "Usage: $0 {start|stop|restart|status}"
            exit 1
    esac

    exit 0